version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 9000
    volumes:
      - ./:/var/www/html
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_DATABASE: 'users'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  mysqldata: {}